
const DATABASE_NAME = process.env.DATABASE_NAME;
const DATABASE_USERNAME = process.env.DATABASE_USERNAME;
const PASSWORD = process.env.PASSWORD;
const SERVER_HOSTNAME = process.env.SERVER_HOSTNAME;

export { DATABASE_NAME, DATABASE_USERNAME, PASSWORD, SERVER_HOSTNAME };
